version: "3"
services:

  mongo:
    image: mongo
    ports:
      - "27017:27017"

  backend:
    build: ./backend
    image: gajendra1/backend-jenkins-test:latest
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    image: gajendra1/frontend-jenkins-test:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend
